source 'https://rubygems.org'

# Rails version
gem 'rails', '4.1.4'

# Postgresql database
gem 'pg','0.17.1'       

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby      # To run your javascript - can use Nodejs

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'     # Use jquery for the UI

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
#gem 'jbuilder', '~> 1.2'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# My Additional Gems
gem 'haml','4.0.5'                          # HTML shortcut
gem 'simple_form', '~>3.0.1'                # Forms shortcut
