# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DEV_DB'] %>
  pool: 5
  username: <%= ENV['DEV_USER'] %> 
  password: <%= ENV['DEV_PASS'] %>

test: &test
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['TEST_DB'] %>
  pool: 5
  username: <%= ENV['TEST_USER'] %> 
  password: <%= ENV['TEST_PASS'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PROD_DB'] %>
  pool: 5
  username: <%= ENV['PROD_USER'] %>
  password: <%= ENV['PROD_PASS'] %>
  host: <%= ENV['PROD_HOST'] %>